export enum VerifierStatus {
    ACTIVATE = 'ACTIVATE',
    DEACTIVATE = 'DEACTIVATE',
    DID_DOCUMENT_REQUIRED = 'DID_DOCUMENT_REQUIRED',
    DID_DOCUMENT_REQUESTED = 'DID_DOCUMENT_REQUESTED',
    CERTIFICATE_VC_REQUIRED = 'CERTIFICATE_VC_REQUIRED',
}
